name: dentist_appointment
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  intl: ^0.19.0
  percent_indicator: ^4.0.1
  ionicons: ^0.2.2
  cupertino_icons: ^1.0.6
  image_picker: ^1.1.0
  sqflite: ^2.3.3
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  fluttertoast: ^8.0.4
  form_field_validator: ^1.1.0
  cloud_firestore: ^4.17.2
  slide_countdown: ^0.3.1
  email_validator: ^2.1.17
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1
  google_sign_in: ^5.2.1
  firebase_auth_oauth: ^0.3.2
  flutter_facebook_auth: ^4.0.0
  sign_in_with_apple: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - lib/Photo/BannerAnimate.png
