name: dentist_appointment
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  intl: ^0.18.1  # Update this line
  percent_indicator: ^4.0.1
  ionicons: ^0.2.2
  cupertino_icons: ^1.0.6
  image_picker: ^1.1.0
  sqflite: ^2.3.3
  slide_countdown: ^0.3.1




  unicons: any
  # flutter_firebase: any



  #Mobile Design Lib
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1
  flutter_localization: ^0.2.0
  flutter_launcher_icons: ^0.13.1
  lottie: ^1.2.1


  #Fire-base 
  http: ^1.2.1
  firebase_core: ^2.30.1
  get: ^4.6.6
  get_storage: ^2.1.1 
  firebase_database: ^10.5.4
  google_sign_in: ^6.2.1
  firebase_auth: ^4.19.4
  firebase_app_check: ^0.2.2+4
  email_validator: ^2.1.17  
  provider: ^6.1.2

flutter_icons: 
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  iconPath: "assets/app_icon.png"

  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - lib/Photo/BannerAnimate.png
