// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkgpeAKG6Up2-nODfG46zX46SygmTsFFc',
    appId: '1:924655253853:web:00aadb34adcb17d5ecd0b4',
    messagingSenderId: '924655253853',
    projectId: 'seez-643cf',
    authDomain: 'seez-643cf.firebaseapp.com',
    storageBucket: 'seez-643cf.appspot.com',
    measurementId: 'G-KJP0Q56Q39',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAfQP2jldmM-9nw9c36m62cmLt_ebIpLk',
    appId: '1:924655253853:android:714a21a2b79d99f7ecd0b4',
    messagingSenderId: '924655253853',
    projectId: 'seez-643cf',
    storageBucket: 'seez-643cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnRMwu98nCzDJ4-nx4KWkSayOVLNwa1K8',
    appId: '1:924655253853:ios:bbcf5bf60d59a67eecd0b4',
    messagingSenderId: '924655253853',
    projectId: 'seez-643cf',
    storageBucket: 'seez-643cf.appspot.com',
    iosBundleId: 'com.example.b',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnRMwu98nCzDJ4-nx4KWkSayOVLNwa1K8',
    appId: '1:924655253853:ios:bbcf5bf60d59a67eecd0b4',
    messagingSenderId: '924655253853',
    projectId: 'seez-643cf',
    storageBucket: 'seez-643cf.appspot.com',
    iosBundleId: 'com.example.b',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkgpeAKG6Up2-nODfG46zX46SygmTsFFc',
    appId: '1:924655253853:web:f5e041aad491a2b6ecd0b4',
    messagingSenderId: '924655253853',
    projectId: 'seez-643cf',
    authDomain: 'seez-643cf.firebaseapp.com',
    storageBucket: 'seez-643cf.appspot.com',
    measurementId: 'G-2FZK56RDEK',
  );

}